#!/usr/bin/env php
<?php

if (!str_contains(strtolower(basename(__DIR__)), 'teenhealth')) {
    echo "Sorry, this command is not allowed.\n";
    exit(1);
}

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
